### ISSUE TITLE
Support environment configuration

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/depreman#50]
Add support to `depreman` to ingest a configuration object from the environment.

The main use case I envision for this is that a user runs `depreman` in their CI on a regular schedule for their latest release (with the goal of knowing when a new release is necessary due to a deprecated dependency). But sometimes a deprecated dependency does not warrant a new release, hence you'd want to instruct `depreman` to ignore it. But in this scenario you can't push a commit with an updated `depreman` config because then it wouldn't be the release commit anymore. Hence you'd need some alternative way to do this.

For example, with GitHub Actions one could specify the config as a [`vars` variable](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#using-the-vars-context-to-access-configuration-variable-values) and provide it to Depreman as an [`env` variable](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idenv).

**Comment by ericcornelissen** [comment]
The following approach is recommended for CI setups for the time being:

```yaml
# Load the configuration for the GitHub Actions variables
# that can be configured in the repository settings. Use
# 'tee' so that you can see what configuration was used in
# the logs at a later point in time (useful if you make
# changes).
- name: Insert custom configuration
  env:
    NDMRC: ${{ vars.NDMRC }}
  run: echo "${NDMRC}" | tee .ndmrc

# And then just use depreman as usual, e.g.
- name: Audit deprecation warnings
  run: npx depreman --errors-only
```
